export const EMV_TAGS: Record<number, string> = {
  0x4F: 'Application Identifier (AID)',
  0x50: 'Application Label',
  0x57: 'Track 2 Equivalent Data',
  0x5A: 'Application PAN',
  0x5F20: 'Cardholder Name',
  0x5F24: 'Application Expiration Date',
  0x5F25: 'Application Effective Date',
  0x5F28: 'Issuer Country Code',
  0x5F2A: 'Transaction Currency Code',
  0x5F2D: 'Language Preference',
  0x5F30: 'Service Code',
  0x5F34: 'PAN Sequence Number',
  0x5F36: 'Transaction Currency Exponent',
  0x5F50: 'Issuer URL',
  0x61: 'Application Template',
  0x6F: 'FCI Template',
  0x70: 'EMV Record Template',
  0x71: 'Issuer Script Template 1',
  0x72: 'Issuer Script Template 2',
  0x77: 'Response Message Template Format 2',
  0x80: 'Response Message Template Format 1',
  0x81: 'Amount Authorised (Binary)',
  0x82: 'Application Interchange Profile',
  0x83: 'Command Template',
  0x84: 'DF Name',
  0x86: 'Issuer Script Command',
  0x87: 'Application Priority Indicator',
  0x88: 'Short File Identifier (SFI)',
  0x89: 'Authorisation Identification Response',
  0x8A: 'Authorisation Response Code',
  0x8C: 'CDOL1',
  0x8D: 'CDOL2',
  0x8E: 'CVM List',
  0x8F: 'CA Public Key Index',
  0x90: 'Issuer Public Key Certificate',
  0x91: 'Issuer Authentication Data',
  0x92: 'Issuer Public Key Remainder',
  0x93: 'Signed Static Application Data',
  0x94: 'Application File Locator',
  0x95: 'Terminal Verification Results',
  0x98: 'TC Hash Value',
  0x99: 'Transaction PIN Data',
  0x9A: 'Transaction Date',
  0x9B: 'Transaction Status Information',
  0x9C: 'Transaction Type',
  0x9D: 'Directory Definition File',
  0x9F01: 'Acquirer Identifier',
  0x9F02: 'Amount Authorised (Numeric)',
  0x9F03: 'Amount Other (Numeric)',
  0x9F04: 'Amount Other (Binary)',
  0x9F05: 'Application Discretionary Data',
  0x9F06: 'AID (Terminal)',
  0x9F07: 'Application Usage Control',
  0x9F08: 'Application Version Number',
  0x9F09: 'Application Version Number (Terminal)',
  0x9F0D: 'IAC Default',
  0x9F0E: 'IAC Denial',
  0x9F0F: 'IAC Online',
  0x9F10: 'Issuer Application Data',
  0x9F11: 'Issuer Code Table Index',
  0x9F12: 'Application Preferred Name',
  0x9F13: 'Last Online ATC',
  0x9F14: 'Lower Consecutive Offline Limit',
  0x9F15: 'Merchant Category Code',
  0x9F16: 'Merchant Identifier',
  0x9F17: 'PIN Try Counter',
  0x9F18: 'Issuer Script Identifier',
  0x9F1A: 'Terminal Country Code',
  0x9F1B: 'Terminal Floor Limit',
  0x9F1C: 'Terminal Identification',
  0x9F1D: 'Terminal Risk Management Data',
  0x9F1E: 'IFD Serial Number',
  0x9F1F: 'Track 1 Discretionary Data',
  0x9F21: 'Transaction Time',
  0x9F22: 'CA Public Key Index (Terminal)',
  0x9F23: 'Upper Consecutive Offline Limit',
  0x9F26: 'Application Cryptogram',
  0x9F27: 'Cryptogram Information Data',
  0x9F2D: 'ICC PIN Encipherment Public Key Certificate',
  0x9F32: 'Issuer Public Key Exponent',
  0x9F33: 'Terminal Capabilities',
  0x9F34: 'CVM Results',
  0x9F35: 'Terminal Type',
  0x9F36: 'Application Transaction Counter',
  0x9F37: 'Unpredictable Number',
  0x9F38: 'PDOL',
  0x9F39: 'POS Entry Mode',
  0x9F3A: 'Amount Reference Currency',
  0x9F3B: 'Application Reference Currency',
  0x9F3C: 'Transaction Reference Currency Code',
  0x9F3D: 'Transaction Reference Currency Exponent',
  0x9F40: 'Additional Terminal Capabilities',
  0x9F41: 'Transaction Sequence Counter',
  0x9F42: 'Application Currency Code',
  0x9F43: 'Application Reference Currency Exponent',
  0x9F44: 'Application Currency Exponent',
  0x9F45: 'Data Authentication Code',
  0x9F46: 'ICC Public Key Certificate',
  0x9F47: 'ICC Public Key Exponent',
  0x9F48: 'ICC Public Key Remainder',
  0x9F49: 'DDOL',
  0x9F4A: 'Static Data Authentication Tag List',
  0x9F4C: 'ICC Dynamic Number',
  0xA5: 'FCI Proprietary Template',
  0xBF0C: 'FCI Issuer Discretionary Data'
};

export function getTagName(tag: number): string {
  return EMV_TAGS[tag] ?? `Unknown (0x${tag.toString(16).toUpperCase()})`;
}
