export const EMV_TAGS: Record<number, string> = {
  0x4f: 'Application Identifier (AID)',
  0x50: 'Application Label',
  0x57: 'Track 2 Equivalent Data',
  0x5a: 'Application PAN',
  0x5f20: 'Cardholder Name',
  0x5f24: 'Application Expiration Date',
  0x5f25: 'Application Effective Date',
  0x5f28: 'Issuer Country Code',
  0x5f2a: 'Transaction Currency Code',
  0x5f2d: 'Language Preference',
  0x5f30: 'Service Code',
  0x5f34: 'PAN Sequence Number',
  0x5f36: 'Transaction Currency Exponent',
  0x5f50: 'Issuer URL',
  0x61: 'Application Template',
  0x6f: 'FCI Template',
  0x70: 'EMV Record Template',
  0x71: 'Issuer Script Template 1',
  0x72: 'Issuer Script Template 2',
  0x77: 'Response Message Template Format 2',
  0x80: 'Response Message Template Format 1',
  0x81: 'Amount Authorised (Binary)',
  0x82: 'Application Interchange Profile',
  0x83: 'Command Template',
  0x84: 'DF Name',
  0x86: 'Issuer Script Command',
  0x87: 'Application Priority Indicator',
  0x88: 'Short File Identifier (SFI)',
  0x89: 'Authorisation Identification Response',
  0x8a: 'Authorisation Response Code',
  0x8c: 'CDOL1',
  0x8d: 'CDOL2',
  0x8e: 'CVM List',
  0x8f: 'CA Public Key Index',
  0x90: 'Issuer Public Key Certificate',
  0x91: 'Issuer Authentication Data',
  0x92: 'Issuer Public Key Remainder',
  0x93: 'Signed Static Application Data',
  0x94: 'Application File Locator',
  0x95: 'Terminal Verification Results',
  0x98: 'TC Hash Value',
  0x99: 'Transaction PIN Data',
  0x9a: 'Transaction Date',
  0x9b: 'Transaction Status Information',
  0x9c: 'Transaction Type',
  0x9d: 'Directory Definition File',
  0x9f01: 'Acquirer Identifier',
  0x9f02: 'Amount Authorised (Numeric)',
  0x9f03: 'Amount Other (Numeric)',
  0x9f04: 'Amount Other (Binary)',
  0x9f05: 'Application Discretionary Data',
  0x9f06: 'AID (Terminal)',
  0x9f07: 'Application Usage Control',
  0x9f08: 'Application Version Number',
  0x9f09: 'Application Version Number (Terminal)',
  0x9f0d: 'IAC Default',
  0x9f0e: 'IAC Denial',
  0x9f0f: 'IAC Online',
  0x9f10: 'Issuer Application Data',
  0x9f11: 'Issuer Code Table Index',
  0x9f12: 'Application Preferred Name',
  0x9f13: 'Last Online ATC',
  0x9f14: 'Lower Consecutive Offline Limit',
  0x9f15: 'Merchant Category Code',
  0x9f16: 'Merchant Identifier',
  0x9f17: 'PIN Try Counter',
  0x9f18: 'Issuer Script Identifier',
  0x9f1a: 'Terminal Country Code',
  0x9f1b: 'Terminal Floor Limit',
  0x9f1c: 'Terminal Identification',
  0x9f1d: 'Terminal Risk Management Data',
  0x9f1e: 'IFD Serial Number',
  0x9f1f: 'Track 1 Discretionary Data',
  0x9f21: 'Transaction Time',
  0x9f22: 'CA Public Key Index (Terminal)',
  0x9f23: 'Upper Consecutive Offline Limit',
  0x9f26: 'Application Cryptogram',
  0x9f27: 'Cryptogram Information Data',
  0x9f2d: 'ICC PIN Encipherment Public Key Certificate',
  0x9f32: 'Issuer Public Key Exponent',
  0x9f33: 'Terminal Capabilities',
  0x9f34: 'CVM Results',
  0x9f35: 'Terminal Type',
  0x9f36: 'Application Transaction Counter',
  0x9f37: 'Unpredictable Number',
  0x9f38: 'PDOL',
  0x9f39: 'POS Entry Mode',
  0x9f3a: 'Amount Reference Currency',
  0x9f3b: 'Application Reference Currency',
  0x9f3c: 'Transaction Reference Currency Code',
  0x9f3d: 'Transaction Reference Currency Exponent',
  0x9f40: 'Additional Terminal Capabilities',
  0x9f41: 'Transaction Sequence Counter',
  0x9f42: 'Application Currency Code',
  0x9f43: 'Application Reference Currency Exponent',
  0x9f44: 'Application Currency Exponent',
  0x9f45: 'Data Authentication Code',
  0x9f46: 'ICC Public Key Certificate',
  0x9f47: 'ICC Public Key Exponent',
  0x9f48: 'ICC Public Key Remainder',
  0x9f49: 'DDOL',
  0x9f4a: 'Static Data Authentication Tag List',
  0x9f4c: 'ICC Dynamic Number',
  0xa5: 'FCI Proprietary Template',
  0xbf0c: 'FCI Issuer Discretionary Data',
};

export function getTagName(tag: number): string {
  return EMV_TAGS[tag] ?? `Unknown (0x${tag.toString(16).toUpperCase()})`;
}
